name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../frontend && npm install
          cd ..

      - name: Run API tests with coverage
        run: |
          npm install -g nyc
          nyc --reporter=lcov --reporter=text npx jest tests/api.test.js

      - name: Install Playwright
        run: npx playwright install

      - name: Run UI tests
        run: npx playwright test tests/ui.test.js
